package bg.softuni.online_library_system.model.enums;

public enum BookGenreEnum {
    ADVENTURE,
    ART,
    AUTOBIOGRAPHY,
    BIOGRAPHY,
    CLASSIC,
    COMEDY,
    COMIC_BOOK,
    CRIME,
    DYSTOPIA,
    FAIRY_TALES,
    FANTASY,
    FICTION,
    GAME_BOOK,
    HISTORICAL_FICTION,
    HISTORICAL,
    HOBBY,
    HORROR,
    HUMOR,
    MANGA,
    MEDICAL,
    MEMOIR,
    MYSTERY,
    NON_FICTION,
    NOVEL,
    PICTURE_BOOK,
    POETRY,
    ROMANCE,
    SCIENCE_FICTION,
    SCIENCE,
    TECHNOLOGY,
    THRILLER
}